{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "sso-keycloak.fullname" . }}
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs:
  - get
  - list
- apiGroups: [""]
  resources: ["pods"]
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "sso-keycloak.fullname" . }}
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sso-keycloak.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "sso-keycloak.fullname" . }}
---
{{- end }}
