{{- $secretName := "otp-credentials" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- $index := 1 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $secret  ( not .Values.otpCredentials.recreateCredentials ) }}
  PPID_API_TOKEN_URL: {{ index $secret.data (print "PPID_API_TOKEN_URL") }}
  PPID_API_URL: {{ index $secret.data (print "PPID_API_URL") }}
  PPID_CLIENT_ID: {{ index $secret.data (print "PPID_CLIENT_ID") }}
  PPID_CLIENT_SECRET: {{ index $secret.data (print "PPID_CLIENT_SECRET") }}
  PPID_OTP_ISSUER: {{ index $secret.data (print "PPID_OTP_ISSUER") }}
  {{- else }}
  PPID_API_TOKEN_URL: {{ default "update me" .Values.otpCredentials.apiTokenUrl | b64enc }}
  PPID_API_URL: {{ default "update me" .Values.otpCredentials.apiUrl | b64enc }}
  PPID_CLIENT_ID: {{ default "update me" .Values.otpCredentials.clientID | b64enc }}
  PPID_CLIENT_SECRET: {{ default "update me" .Values.otpCredentials.clientSecret | b64enc }}
  PPID_OTP_ISSUER: {{ default "update me" .Values.otpCredentials.otpIssuer | b64enc }}
  {{- end }}
