{{- $secretName := "otp-credentials" }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName ) }}
{{- $index := 1 }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and $secret  ( not values.otpCredentials.recreateCredentials ) }}
  PPID_API_TOKEN_URL: {{ index $secret.data (print "PPID_API_TOKEN_URL") }}
  PPID_API_URL: {{ index $secret.data (print "PPID_API_URL") }}
  PPID_CLIENT_ID: {{ index $secret.data (print "PPID_CLIENT_ID") }}
  PPID_CLIENT_SECRET: {{ index $secret.data (print "PPID_CLIENT_SECRET") }}
  PPID_OTP_ISSUER: {{ index $secret.data (print "PPID_OTP_ISSUER") }}
  {{- else }}
  PPID_API_TOKEN_URL: {{ values.otpCredentials.apiTokenUrl | default ("update me") | b64enc }}
  PPID_API_URL: {{ values.otpCredentials.apiUrl | default ("update me") | b64enc }}
  PPID_CLIENT_ID: {{ values.otpCredentials.clientID | default ("update me") | b64enc }}
  PPID_CLIENT_SECRET: {{ values.otpCredentials.clientSecret | default ("update me") | b64enc }}
  PPID_OTP_ISSUER: {{ values.otpCredentials.otpIssuer | default ("update me") | b64enc }}
  {{- end }}
