{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sso-keycloak.fullname" . }}
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
{{- end }}
