apiVersion: v1
kind: Service
metadata:
  name: {{ include "sso-keycloak.fullname" . }}-ping
  labels: {{ include "sso-keycloak.labels" . | nindent 4 }}
  annotations:
    description: "The headless service for the keycloak stateful set."
spec:
  clusterIP: None
  ports:
    {{- if .Values.tls.enabled }}
    - name: https
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: https
    {{- else }}
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    {{- end }}
  selector: {{ include "sso-keycloak.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
