replicaCount: 1

image:
  repository: ghcr.io/bcgov/pathfinder-sso/saml-playground
  tag: dev
  pullPolicy: Always

nameOverride: saml-playground
fullnameOverride: saml-playground

service:
  type: ClusterIP
  port: 8080

route:
  host:

env:
  APP_URI: "https://saml-playground-c6af30-dev.apps.gold.devops.gov.bc.ca"
  SERVER_PORT: 8080

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi
